title: Thrift Savings Plan
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beta.tsp.gov" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-last-modified-at

theme: uswds-jekyll

# My Account URLS
myaccount: "https://www.tsp.gov/tsp"
profile_settings: "https://www.tsp.gov/tsp/profileSettings.do?subaction=view&amp;_name=profile"
# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: beta.tsp

# Configuration for Google Analytics, add your UA code here:
# google_analytics_ua: UA-33523145-2
google_analytics_ua: UA-155812092-1

# Configuration for DAP, add your agency ID here:
dap_agency: FRTIB&pua=ua-33523145-2"

# Build settings
markdown: kramdown

scripts:
  - /assets/uswds/js/uswds.min.js
  - /assets/js/vendor/glossary.min.js
  - /assets/js/glossary.js
  - /assets/js/dialog.js
  - /assets/js/usa-search.js

# Compress Sass
# sass:
#   style: compressed

exclude:
  - circle.yml
  - README.md
  - package-lock.json
  - package.json
  - vendor
  - styleguide

keep_files:
  - styleguide

# output: true will copy the collection into _site
collections:
  funds:
    output: true
  forms:
    output: true
  plan_news:
    output: true
  publications:
    output: true
  newsletters:
    output: true
  faq:
    output: true

defaults:
  -
    scope:
      path: "_plan_news"
    values:
      layout: page-plan-news
      sidenav: news-and-resources
  -
    scope:
      path: "_faq"
    values:
      layout: page-faq
      sidenav: news-and-resources
