label: Alerts
status: ready
preview: '@preview'


variants:
  - name: default
    context:
      alert:
        alert_type:
        heading: Default callout box

  - name: Error
    context:
      alert:
        alert_type: error
        heading: Error callout box

  - name: Info
    context:
      alert:
        alert_type: info
        heading: Info callout box

  - name: Success
    context:
      alert:
        alert_type: success
        heading: Success callout box
